### ISSUE TITLE
(1.0.2) Cannot enter text into the Terminal app

### ISSUE THREAD

**Issue by mcthomas** [jhhoward/Ardutosh#1]
I cannot enter text into the Terminal app, though everything else works as described.  I both flashed it with the hex and after building from source, but the problem persists.

**Comment by jhhoward** [comment]
Is the Arduboy serial attached to anything? (e.g. Arduino serial monitor or PuTTY)

**Comment by mcthomas** [comment]
Nope, I attach it to my MacBook to flash it and then it is disconnected when in use.

**Comment by jhhoward** [comment]
OK the way the terminal app is supposed to work is that you attach the Arduboy to another device and it acts like a serial terminal. For example you could connect to a raspberry pi and then login to a shell and run commands (provided you have configured your computer to accept login through serial connections).

If you don't have anything attached then it won't do much :)

**Comment by mcthomas** [comment]
Oh I'm so sorry, I thought it was more of just an emulator for fun.  That makes sense, thank you for your quick responses.
